export const booksContants = {
  GET_ALL_BOOKS: 'GET_ALL_BOOKS',
  GET_BOOK_BY_ID: 'GET_BOOK_BY_ID',
  EDIT_BOOK_BY_ID: 'EDIT_BOOK_BY_ID',
  ADD_BOOK: 'ADD_BOOK',
  DELETE_BOOK: 'DELETE_BOOK',
  BOOK_NAO_ENCONTRADO: 'BOOK_NAO_ENCONTRADO'
}